add docker

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -15,7 +15,10 @@ jobs:
       DATABASE_URL: ${{ secrets.DATABASE_URL }}
       JWT_SECRET: ${{ secrets.JWT_SECRET }}
       REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
-
+      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+      EXAMINER_ID: ${{ secrets.EXAMINER_ID }}
+      #NODE_OPTIONS: --max_old_space_size=4096
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
@@ -41,10 +44,41 @@ jobs:
         working-directory: src/backend
         run: npm run test
 
-      - name: format code
+      - name: Format code
         working-directory: src/backend
         run: npm run prettier
 
       - name: Check code formatting
         working-directory: src/backend
         run: npm run prettier:check
+
+      # - name: Login to Docker Hub
+      #   run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
+      - name: Log in to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+      - name: Build Docker image
+        working-directory: src/backend
+        run: docker build -t ${{secrets.DOCKER_USERNAME}}/examinator-backend:latest  .
+      - name: Push Docker image
+        run: docker push ${{ secrets.DOCKER_USERNAME }}/examinator-backend:latest
+      - name: Run container
+        run: |
+          docker run -d \
+            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
+            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
+            -e REFRESH_TOKEN=${{ secrets.REFRESH_TOKEN }} \
+            -p 5001:5001 \
+            ${{ secrets.DOCKER_USERNAME }}/examinator-backend:latest
+
+      - name: Wait for app and show container status
+        run: |
+          sleep 5
+          docker ps
+          docker logs $(docker ps -q)
+
+      - name: Test health endpoint
+        run: |
+          curl http://localhost:5001/api/exam/exams/${{secrets.EXAMINER_ID}} || echo "Health check failed"
